### ISSUE TITLE
DrawableMatcher # isSameDrawable doesn't work when SDK_INT >= LOLLIPOP

### ISSUE THREAD

**Issue by thyrlian** [hitherejoe/Vineyard#3]
[DrawableMatcher # isSameDrawable](https://github.com/hitherejoe/Vineyard/blob/fd8f61d2b9427269aa0268e4afb94b54ede0277a/app/src/androidTest/java/com/hitherejoe/vineyard/util/DrawableMatcher.java#L85)

```java
private boolean isSameDrawable(Drawable drawable) {
    if (drawable == null) {
        return false;
    }
    return expectedDrawable.getConstantState().equals(drawable.getConstantState());
}
```

The problem is:
When SDK_INT >= LOLLIPOP
```java
expectedDrawable = context.getDrawable(resourceId); // expectedDrawable will be a BitmapDrawable
actualDrawable = target.getBackground(); // actualDrawable will be a RippleDrawable
```
And unfortunately ***getConstantState()*** on these two different types of instances are not the same.

After browsing through the API documentation of [BitmapDrawable](http://developer.android.com/reference/android/graphics/drawable/BitmapDrawable.html) and [RippleDrawable](http://developer.android.com/reference/android/graphics/drawable/RippleDrawable.html), I can't really find a useful getter which could identify they are the same resource.

**Comment by hitherejoe** [comment]
Ah yes I planned do revisiting this as I questioned it's reliability (passes on my ADT-1 lollipop). The test isn't really necessary anyway so I'll remove it. But thanks for pointing it out!

**Comment by thyrlian** [comment]
Aha, good to know :)

Please keep me updated once you find a way to make this work in any of your other projects, thanks.

**Comment by hitherejoe** [comment]
Will do! :)
